name: release
on:
  push:
    tags:
    - "v*.*.*"
jobs:
  publish-dist:
    runs-on: ubuntu-latest
    env:
      DRONE_TAG: ${{github.ref_name}}
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make
    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/artifacts/rancherd-amd64